import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
test('asset inventory is tenant scoped and records privacy classification',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/organization_id uuid NOT NULL/);assert.match(s,/contains_pii boolean/);assert.match(s,/data_classification/);assert.match(s,/requireOrgPermission\(userId,organizationId,'manageAssessment'\)/)});
test('coverage cannot be complete without evidence',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/Complete assessment layer requires persisted evidence/);assert.match(s,/evidence_count/);assert.match(s,/failure_reasons/)});
test('server initializes persistent assessment inventory',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/await initAssessmentInventory\(\)/);assert.match(s,/assessments\/:assessmentId\/coverage/);assert.match(s,/organizations\/:orgId\/assets/)});

test('infrastructure OpenVAS evidence ingestion is fail closed',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/openvas-report/);assert.match(s,/OPENVAS_REPORT_INGESTED/);assert.match(s,/Report contained no parseable OpenVAS vulnerability results; assessment coverage was not advanced/);assert.match(s,/source:'openvas'/)});

test('infrastructure completion requires successful Nmap and OpenVAS evidence',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/Nmap successful evidence missing/);assert.match(s,/OpenVAS successful evidence missing/);assert.match(s,/nmap&&openvas\?'COMPLETE':'PARTIAL'/);assert.match(s,/timedOut/);assert.match(s,/stdoutTruncated/);assert.match(s,/stderrTruncated/)});
test('server exposes authoritative infrastructure reconciliation endpoint',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/infrastructure\/reconcile/);assert.match(s,/reconcileInfrastructureCoverage/)});

test('OpenVAS targeted retest is server-bound to original infrastructure finding',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/openvas-retest/);assert.match(s,/original\.source!=='openvas'/);assert.match(s,/originalFingerprint:fingerprint/);assert.match(s,/scannerSource:'openvas'/);assert.match(s,/stillPresent\?409:200/);assert.match(s,/TARGETED_RETEST_COMPLETED/)});

test('assessment coverage lifecycle enforces assessment organization ownership',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/requireAssessmentAccess/);assert.match(s,/Assessment does not belong to this organization/);});

test('inventory validates scope ownership booleans metadata status and initialized layer',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/Scope does not belong to this organization/);assert.match(s,/containsPii must be boolean/);assert.match(s,/metadata must be an object/);assert.match(s,/Invalid assessment layer status/);assert.match(s,/Assessment layer is not initialized/);});

test('endpoint coverage requires persisted Wazuh evidence',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/reconcileEndpointCoverage/);assert.match(s,/Wazuh endpoint evidence missing/);assert.match(s,/requiredEngines:\['WAZUH'\]/)});
test('endpoint routes bind Wazuh ingest and retest to assessment and fingerprint',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/wazuh-report/);assert.match(s,/endpoint\/reconcile/);assert.match(s,/wazuh-retest/);assert.match(s,/original\.source!=='wazuh'/);assert.match(s,/scannerSource:'wazuh'/);assert.match(s,/stillPresent\?409:200/)});

test('web coverage requires successful ZAP and Nuclei evidence',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/reconcileWebCoverage/);assert.match(s,/ZAP successful web evidence missing/);assert.match(s,/Nuclei successful web evidence missing/);assert.match(s,/zap&&nuclei\?'COMPLETE':'PARTIAL'/)});
test('server exposes authoritative web reconciliation',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/web\/reconcile/);assert.match(s,/reconcileWebCoverage/)});

test('infrastructure evidence count evaluates each evidence row independently',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/const validEvidence=/);assert.match(s,/count=ev\.filter\(validEvidence\)\.length/)});

test('API coverage requires successful ZAP and Nuclei evidence',async()=>{const s=await readFile(new URL('../src/assessment-inventory.ts',import.meta.url),'utf8');assert.match(s,/reconcileApiCoverage/);assert.match(s,/ZAP successful API evidence missing/);assert.match(s,/Nuclei successful API evidence missing/);assert.match(s,/API layer is not initialized/)});
test('server exposes authoritative API reconciliation',async()=>{const s=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(s,/api\/reconcile/);assert.match(s,/reconcileApiCoverage/)});
