export type IntelItem={title:string;link:string;publishedAt:string;source:string;summary:string;category:string;cve?:string;knownExploited?:boolean;dueDate?:string};
const feeds=[{source:'CISA Advisories',url:'https://www.cisa.gov/cybersecurity-advisories/all.xml',category:'Advisory'},{source:'NIST News',url:'https://www.nist.gov/news-events/news/rss.xml',category:'Research'}];
function clean(s:string){return s.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function value(block:string,name:string){const a=block.toLowerCase().indexOf('<'+name.toLowerCase());if(a<0)return '';const start=block.indexOf('>',a)+1,end=block.toLowerCase().indexOf('</'+name.toLowerCase()+'>',start);return end<0?'':clean(block.slice(start,end).replace('<![CDATA[','').replace(']]>',''))}
async function feed(source:string,url:string,category:string){const r=await fetch(url,{headers:{'User-Agent':'AegisGRC-Security'}});if(!r.ok)throw Error(source+' unavailable');const xml=await r.text(),out:IntelItem[]=[];for(const block of xml.split('<item').slice(1,16)){const title=value(block,'title'),link=value(block,'link'),summary=value(block,'description').slice(0,600);if(title&&link)out.push({title,link,publishedAt:value(block,'pubDate'),source,summary,category,cve:(title+' '+summary).match(/CVE-\d{4}-\d{4,}/i)?.[0].toUpperCase()})}return out}
async function kev(){const url='https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',r=await fetch(url,{headers:{'User-Agent':'AegisGRC-Security'}});if(!r.ok)throw Error('CISA KEV unavailable');const d:any=await r.json();return (d.vulnerabilities||[]).slice(-25).reverse().map((v:any):IntelItem=>({title:v.cveID+' · '+v.vulnerabilityName,link:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog',publishedAt:v.dateAdded,source:'CISA KEV',summary:(v.shortDescription||'')+' Required action: '+(v.requiredAction||''),category:'Known Exploited',cve:v.cveID,knownExploited:true,dueDate:v.dueDate}))}
let cache:{at:number,items:IntelItem[],errors:string[]}|null=null;
export async function cyberIntel(force=false){if(!force&&cache&&Date.now()-cache.at<900000)return {...cache,cache:'HIT'};const jobs=[...feeds.map(x=>feed(x.source,x.url,x.category)),kev()],results=await Promise.allSettled(jobs),items:IntelItem[]=[],errors:string[]=[];results.forEach((x,i)=>x.status==='fulfilled'?items.push(...x.value):errors.push(i<feeds.length?feeds[i].source:'CISA KEV'));items.sort((a,b)=>Date.parse(b.publishedAt||'0')-Date.parse(a.publishedAt||'0'));cache={at:Date.now(),items:items.slice(0,50),errors};return {...cache,cache:'REFRESHED'}}
export async function nvdCve(cve:string){if(!/^CVE-\d{4}-\d{4,}$/i.test(cve))throw Error('Invalid CVE');const r=await fetch('https://services.nvd.nist.gov/rest/json/cves/2.0?cveId='+encodeURIComponent(cve.toUpperCase()),{headers:{'User-Agent':'AegisGRC-Security'}});if(!r.ok)throw Error('NVD lookup unavailable');const d:any=await r.json(),v=d.vulnerabilities?.[0]?.cve;if(!v)return {cve:cve.toUpperCase(),found:false};const metric=v.metrics?.cvssMetricV31?.[0]||v.metrics?.cvssMetricV40?.[0]||v.metrics?.cvssMetricV30?.[0]||v.metrics?.cvssMetricV2?.[0],data=metric?.cvssData||{};return {cve:v.id,found:true,published:v.published,lastModified:v.lastModified,description:v.descriptions?.find((x:any)=>x.lang==='en')?.value||'',cvss:{score:data.baseScore??null,severity:data.baseSeverity||metric?.baseSeverity||null,vector:data.vectorString||null,source:metric?.source||'NVD'},references:(v.references||[]).slice(0,8).map((x:any)=>({url:x.url,tags:x.tags||[]}))}}
