import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx';
import PptxGenJS from 'pptxgenjs';
import * as XLSX from 'xlsx';
import type { Assessment,Finding } from './models.js';
import { frameworkById,frameworkRefs } from './grc.js';

export type ReportKind='grc'|'remediation'|'architecture'|'technical'|'executive';
function rows(fs:Finding[]){return fs.map(f=>({Severity:f.severity,CVSS:f.cvss??'',CWE:f.cwe??'',Title:f.title,Asset:f.asset,Source:f.source,Remediation:f.remediation??'',Evidence:f.evidenceHash,OWASP:(f.mappings.owasp||[]).join('; '),ISO27001:(f.mappings.iso27001||[]).join('; '),ISO42001:(f.mappings.iso42001||[]).join('; '),NIST:(f.mappings.nist||[]).join('; ')}))}
export function reportModel(a:Assessment,fs:Finding[],kind:ReportKind){return {kind,generatedAt:new Date().toISOString(),assessment:{id:a.id,target:a.target,status:a.status,authorizedAt:a.authorizedAt},provenance:'Only stored scanner/document evidence is treated as evidence. AI content is advisory.',findings:rows(fs)}}
export async function docxReport(a:Assessment,fs:Finding[],kind:ReportKind){const m=reportModel(a,fs,kind);const head=['Severity','CVSS','CWE','Title','Source','Remediation'];const table=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:head.map(x=>new TableCell({children:[new Paragraph(x)]}))}),...m.findings.map((r:any)=>new TableRow({children:head.map(k=>new TableCell({children:[new Paragraph(String(r[k]??''))]}))}))]});const d=new Document({sections:[{children:[new Paragraph({text:'AegisGRC '+kind.toUpperCase()+' Report',heading:HeadingLevel.TITLE}),new Paragraph('Target: '+a.target),new Paragraph('Assessment: '+a.id),new Paragraph('Generated: '+m.generatedAt),new Paragraph({text:'Evidence & Remediation',heading:HeadingLevel.HEADING_1}),table]}]});return Packer.toBuffer(d)}
export async function pptxReport(a:Assessment,fs:Finding[],kind:ReportKind){const PptxCtor=(PptxGenJS as any).default ?? PptxGenJS;
 const p=new PptxCtor();p.layout='LAYOUT_WIDE';let s=p.addSlide();s.addText('AegisGRC '+kind.toUpperCase()+' Report',{x:.6,y:.6,w:11.8,h:.6,fontSize:26,bold:true});s.addText('Target: '+a.target+'\nAssessment: '+a.id,{x:.6,y:1.5,w:11,h:1,fontSize:14});const counts=['CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(x=>x+': '+fs.filter(f=>f.severity===x).length).join('   ');s.addText(counts,{x:.6,y:3,w:11,h:.5,fontSize:18});for(const f of fs.slice(0,20)){s=p.addSlide();s.addText(f.severity+' · '+f.title,{x:.5,y:.4,w:12,h:.5,fontSize:22,bold:true});s.addText('CVSS: '+(f.cvss??'N/A')+'   CWE: '+(f.cwe??'N/A')+'   Source: '+f.source,{x:.5,y:1.1,w:12,h:.4,fontSize:13});s.addText('Evidence hash: '+f.evidenceHash+'\n\nRemediation\n'+(f.remediation||'No normalized remediation recorded.'),{x:.5,y:1.8,w:12,h:4.5,fontSize:14,breakLine:true})}return Buffer.from(await p.write({outputType:'nodebuffer'}) as Buffer)}
export function xlsxReport(a:Assessment,fs:Finding[],kind:ReportKind){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows(fs)),'Findings');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Report:kind,Target:a.target,Assessment:a.id,Generated:new Date().toISOString()}]),'Summary');return Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))}
export function csvReport(fs:Finding[]){return Buffer.from(XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows(fs))))}
export function txtReport(a:Assessment,fs:Finding[],kind:ReportKind){const lines=['AegisGRC '+kind.toUpperCase()+' REPORT','Target: '+a.target,'Assessment: '+a.id,'','FINDINGS'];for(const f of fs)lines.push('\n['+f.severity+'] '+f.title+' | CVSS '+(f.cvss??'N/A')+' | '+(f.cwe??'N/A')+'\nSource: '+f.source+'\nEvidence: '+f.evidenceHash+'\nRemediation: '+(f.remediation||'Not recorded'));return Buffer.from(lines.join('\n'))}

export function frameworkReportModel(a:Assessment,fs:Finding[],frameworkId:string){const fw=frameworkById(frameworkId);if(!fw)throw new Error('Unknown framework');const mapped=fs.map(f=>({severity:f.severity,cvss:f.cvss??null,cwe:f.cwe??null,title:f.title,asset:f.asset,source:f.source,evidenceHash:f.evidenceHash,controlReferences:frameworkRefs(f,frameworkId),remediation:f.remediation??'Not recorded'}));return {framework:fw,generatedAt:new Date().toISOString(),assessment:{id:a.id,target:a.target,status:a.status,authorizedAt:a.authorizedAt},disclaimer:'Evidence-backed gap assessment and cross-reference; not a certification or legal determination.',summary:{findings:fs.length,mappedFindings:mapped.filter(x=>x.controlReferences.length).length,unmappedFindings:mapped.filter(x=>!x.controlReferences.length).length},findings:mapped}}
export async function frameworkDocx(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId);const head=['Severity','CVSS','Title','Control references','Remediation'];const rows=m.findings.map((r:any)=>new TableRow({children:[r.severity,r.cvss??'',r.title,r.controlReferences.join('; '),r.remediation].map(x=>new TableCell({children:[new Paragraph(String(x))]}))}));const d=new Document({sections:[{children:[new Paragraph({text:'AegisGRC · '+m.framework.name,heading:HeadingLevel.TITLE}),new Paragraph('Target: '+a.target),new Paragraph('Assessment: '+a.id),new Paragraph(m.disclaimer),new Paragraph({text:'Framework Evidence Matrix',heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:head.map(x=>new TableCell({children:[new Paragraph(x)]}))}),...rows]})]}]});return Packer.toBuffer(d)}
export function frameworkXlsx(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(m.findings.map(x=>({...x,controlReferences:x.controlReferences.join('; ')}))),'Control Matrix');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Framework:m.framework.name,Scope:m.framework.scope,Target:a.target,Assessment:a.id,Generated:m.generatedAt,Findings:m.summary.findings,Mapped:m.summary.mappedFindings}]),'Summary');return Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))}
export function frameworkCsv(fs:Finding[],frameworkId:string){return Buffer.from(XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(fs.map(f=>({Severity:f.severity,CVSS:f.cvss??'',CWE:f.cwe??'',Title:f.title,Asset:f.asset,Source:f.source,Controls:frameworkRefs(f,frameworkId).join('; '),Evidence:f.evidenceHash,Remediation:f.remediation??''})))))}
export function frameworkTxt(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId);return Buffer.from([m.framework.name,'Target: '+a.target,'Assessment: '+a.id,m.disclaimer,'',...m.findings.map(x=>'['+x.severity+'] '+x.title+'\nControls: '+(x.controlReferences.join(', ')||'No deterministic mapping')+'\nEvidence: '+x.evidenceHash+'\nRemediation: '+x.remediation)].join('\n'))}
