import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType, ImageRun } from 'docx';
import PptxGenJS from 'pptxgenjs';
import * as XLSX from 'xlsx';
import type { Assessment,Finding,Evidence } from './models.js';
import { frameworkById,frameworkRefs } from './grc.js';

export type ReportKind='grc'|'remediation'|'architecture'|'technical'|'executive';
function evSummary(ev:Evidence[]){return ev.map(e=>({Tool:e.source,Created:e.createdAt,ExitCode:e.exitCode??'',SHA256:e.sha256,Target:String(e.metadata?.target||''),DurationMs:String(e.metadata?.durationMs||''),Stdout:(e.stdout||'').slice(0,12000),Stderr:(e.stderr||'').slice(0,4000)}))}
function methodology(ev:Evidence[]){const tools=[...new Set(ev.map(e=>e.source.toUpperCase()))];return ['Authorized scope validation','Tools executed: '+(tools.join(', ')||'No stored tool evidence'),'Evidence hashed with SHA-256','Findings normalized with severity/CVSS/CWE where supported','Defensive validation and remediation guidance','Framework cross-reference from evidence-backed findings']}
function rows(fs:Finding[]){return fs.map(f=>({Severity:f.severity,CVSS:f.cvss??'',CWE:f.cwe??'',Title:f.title,Asset:f.asset,Source:f.source,Remediation:f.remediation??'',Evidence:f.evidenceHash,OWASP:(f.mappings.owasp||[]).join('; '),ISO27001:(f.mappings.iso27001||[]).join('; '),ISO42001:(f.mappings.iso42001||[]).join('; '),NIST:(f.mappings.nist||[]).join('; ')}))}
export function reportModel(a:Assessment,fs:Finding[],kind:ReportKind,ev:Evidence[]=[]){return {kind,generatedAt:new Date().toISOString(),assessment:{id:a.id,target:a.target,status:a.status,authorizedAt:a.authorizedAt},provenance:'Only stored scanner/document evidence is treated as evidence. AI content is advisory.',methodology:methodology(ev),toolEvidence:evSummary(ev),findings:rows(fs)}}
function humanFinding(f:Finding){const score=f.cvss==null?'No CVSS was assigned because the available evidence does not establish a scoreable vulnerability.':'CVSS '+f.cvss+' reflects the normalized severity recorded for this finding.';const meaning='What was observed: '+f.description;const impact='Why it matters: '+(f.severity==='CRITICAL'||f.severity==='HIGH'?'This finding deserves priority because successful abuse or exposure could have significant security impact.':f.severity==='MEDIUM'?'This represents a meaningful weakness or exposure that should be addressed through normal remediation priority.':f.severity==='LOW'?'This is a lower-risk weakness or hardening opportunity, but it should still be reviewed in context.':'This is primarily an exposure/observation. It is not, by itself, proof of an exploitable vulnerability.');const action='Recommended action: '+(f.remediation||'Validate business necessity and configuration, apply the appropriate security control, then retest the original evidence path.');const verify='How to verify the fix: repeat the same authorized test that produced this evidence and confirm the condition is no longer present or is restricted as intended.';return [meaning,impact,score,action,verify]}
function summaryLines(fs:Finding[]){const sev=['CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(k=>k+': '+fs.filter(f=>f.severity===k).length);const scored=fs.map(f=>Number(f.cvss)).filter(Number.isFinite);return [...sev,'Highest CVSS: '+(scored.length?Math.max(...scored).toFixed(1):'N/A'),'Evidence-backed findings: '+fs.length]}
export async function docxReport(a:Assessment,fs:Finding[],kind:ReportKind,ev:Evidence[]=[]){const m=reportModel(a,fs,kind,ev);const head=['Severity','CVSS','CWE','Title','Source','Remediation'];const table=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:head.map(x=>new TableCell({children:[new Paragraph(x)]}))}),...m.findings.map((r:any)=>new TableRow({children:head.map(k=>new TableCell({children:[new Paragraph(String(r[k]??''))]}))}))]});const d=new Document({sections:[{children:[new Paragraph({text:'AegisGRC '+kind.toUpperCase()+' Report',heading:HeadingLevel.TITLE}),new Paragraph('Target: '+a.target),new Paragraph('Assessment: '+a.id),new Paragraph('Generated: '+m.generatedAt),new Paragraph({text:'Risk Summary',heading:HeadingLevel.HEADING_1}),...summaryLines(fs).map(x=>new Paragraph(x)),new Paragraph({text:'Assessment flow: Authorized scope → Live/technical tests → SHA-256 evidence → Findings/CVSS → Remediation → GRC mapping → Report'}),new Paragraph({text:'Testing & Evidence',heading:HeadingLevel.HEADING_1}),...m.methodology.map((x:string)=>new Paragraph('• '+x)),...m.toolEvidence.flatMap((e:any)=>[new Paragraph({text:e.Tool+' evidence',heading:HeadingLevel.HEADING_2}),new Paragraph('SHA-256: '+e.SHA256+' | Exit: '+e.ExitCode+' | Duration: '+e.DurationMs+' ms'),new Paragraph((e.Stdout||e.Stderr||'No textual output stored').slice(0,8000))]),new Paragraph({text:'Vulnerability Findings, Defensive Analysis & Remediation',heading:HeadingLevel.HEADING_1}),...fs.flatMap(f=>[new Paragraph({text:f.severity+' · '+f.title,heading:HeadingLevel.HEADING_2}),...humanFinding(f).map(x=>new Paragraph(x)),new Paragraph('Evidence reference: '+f.evidenceHash)]),new Paragraph({text:'Findings Matrix',heading:HeadingLevel.HEADING_1}),table]}]});return Packer.toBuffer(d)}
export async function pptxReport(a:Assessment,fs:Finding[],kind:ReportKind,ev:Evidence[]=[]){const PptxCtor=(PptxGenJS as any).default ?? PptxGenJS;
 const p=new PptxCtor();p.layout='LAYOUT_WIDE';let s=p.addSlide();s.addText('AegisGRC '+kind.toUpperCase()+' Report',{x:.6,y:.6,w:11.8,h:.6,fontSize:26,bold:true});s.addText('Target: '+a.target+'\nAssessment: '+a.id,{x:.6,y:1.5,w:11,h:1,fontSize:14});const counts=['CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(x=>x+': '+fs.filter(f=>f.severity===x).length).join('   ');s.addText(counts,{x:.6,y:3,w:11,h:.5,fontSize:18});s.addText('Testing: '+[...new Set(ev.map(e=>e.source.toUpperCase()))].join(', '),{x:.6,y:3.7,w:11,h:.5,fontSize:14});for(const f of fs.slice(0,20)){s=p.addSlide();s.addText(f.severity+' · '+f.title,{x:.5,y:.4,w:12,h:.5,fontSize:22,bold:true});s.addText('CVSS: '+(f.cvss??'N/A')+'   CWE: '+(f.cwe??'N/A')+'   Source: '+f.source,{x:.5,y:1.1,w:12,h:.4,fontSize:13});s.addText('Evidence hash: '+f.evidenceHash+'\n\nRemediation\n'+(f.remediation||'No normalized remediation recorded.'),{x:.5,y:1.8,w:12,h:4.5,fontSize:14,breakLine:true})}return Buffer.from(await p.write({outputType:'nodebuffer'}) as Buffer)}
export function xlsxReport(a:Assessment,fs:Finding[],kind:ReportKind,ev:Evidence[]=[]){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows(fs)),'Findings');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Report:kind,Target:a.target,Assessment:a.id,Generated:new Date().toISOString()}]),'Summary');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(evSummary(ev)),'Tool Evidence');return Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))}
export function csvReport(fs:Finding[]){return Buffer.from(XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows(fs))))}
export function txtReport(a:Assessment,fs:Finding[],kind:ReportKind,ev:Evidence[]=[]){const lines=['AegisGRC '+kind.toUpperCase()+' REPORT','Target: '+a.target,'Assessment: '+a.id,'','TESTING & EVIDENCE',...methodology(ev),...evSummary(ev).flatMap(e=>['','['+e.Tool+'] SHA-256 '+e.SHA256+' Exit '+e.ExitCode,e.Stdout||e.Stderr]),'','FINDINGS'];for(const f of fs)lines.push('\n['+f.severity+'] '+f.title+' | CVSS '+(f.cvss??'N/A')+' | '+(f.cwe??'N/A')+'\nSource: '+f.source+'\nEvidence: '+f.evidenceHash+'\nRemediation: '+(f.remediation||'Not recorded'));return Buffer.from(lines.join('\n'))}

export function frameworkReportModel(a:Assessment,fs:Finding[],frameworkId:string){const fw=frameworkById(frameworkId);if(!fw)throw new Error('Unknown framework');const mapped=fs.map(f=>({severity:f.severity,cvss:f.cvss??null,cwe:f.cwe??null,title:f.title,asset:f.asset,source:f.source,evidenceHash:f.evidenceHash,controlReferences:frameworkRefs(f,frameworkId),remediation:f.remediation??'Not recorded'}));return {framework:fw,generatedAt:new Date().toISOString(),assessment:{id:a.id,target:a.target,status:a.status,authorizedAt:a.authorizedAt},disclaimer:'Evidence-backed gap assessment and cross-reference; not a certification or legal determination.',summary:{findings:fs.length,mappedFindings:mapped.filter(x=>x.controlReferences.length).length,unmappedFindings:mapped.filter(x=>!x.controlReferences.length).length},findings:mapped}}
export async function frameworkDocx(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId);const head=['Severity','CVSS','Title','Control references','Remediation'];const rows=m.findings.map((r:any)=>new TableRow({children:[r.severity,r.cvss??'',r.title,r.controlReferences.join('; '),r.remediation].map(x=>new TableCell({children:[new Paragraph(String(x))]}))}));const d=new Document({sections:[{children:[new Paragraph({text:'AegisGRC · '+m.framework.name,heading:HeadingLevel.TITLE}),new Paragraph('Target: '+a.target),new Paragraph('Assessment: '+a.id),new Paragraph(m.disclaimer),new Paragraph({text:'Risk & Mapping Summary',heading:HeadingLevel.HEADING_1}),...summaryLines(fs).map(x=>new Paragraph(x)),new Paragraph('Mapped findings: '+m.summary.mappedFindings+' / '+m.summary.findings),new Paragraph({text:'Framework Evidence Matrix',heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:head.map(x=>new TableCell({children:[new Paragraph(x)]}))}),...rows]})]}]});return Packer.toBuffer(d)}
export function frameworkXlsx(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(m.findings.map(x=>({...x,controlReferences:x.controlReferences.join('; ')}))),'Control Matrix');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Framework:m.framework.name,Scope:m.framework.scope,Target:a.target,Assessment:a.id,Generated:m.generatedAt,Findings:m.summary.findings,Mapped:m.summary.mappedFindings}]),'Summary');return Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))}
export function frameworkCsv(fs:Finding[],frameworkId:string){return Buffer.from(XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(fs.map(f=>({Severity:f.severity,CVSS:f.cvss??'',CWE:f.cwe??'',Title:f.title,Asset:f.asset,Source:f.source,Controls:frameworkRefs(f,frameworkId).join('; '),Evidence:f.evidenceHash,Remediation:f.remediation??''})))))}
export function frameworkTxt(a:Assessment,fs:Finding[],frameworkId:string){const m=frameworkReportModel(a,fs,frameworkId);return Buffer.from([m.framework.name,'Target: '+a.target,'Assessment: '+a.id,m.disclaimer,'',...m.findings.map(x=>'['+x.severity+'] '+x.title+'\nControls: '+(x.controlReferences.join(', ')||'No deterministic mapping')+'\nEvidence: '+x.evidenceHash+'\nRemediation: '+x.remediation)].join('\n'))}
