import crypto from 'node:crypto';import pg from 'pg';import {requireOrgPermission} from './grc-organizations.js';
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false},max:Number(process.env.DB_POOL_MAX||30)});
const key=(p:string)=>p+'-'+new Date().getUTCFullYear()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();
export function riskBand(score:number){return score>=20?'CRITICAL':score>=15?'HIGH':score>=8?'MEDIUM':score>=4?'LOW':'VERY_LOW'}
export async function initIssueRiskCapa(){await pool.query(`
ALTER TABLE grc_issues ADD COLUMN IF NOT EXISTS scope_control_id uuid REFERENCES grc_scope_controls(id) ON DELETE SET NULL;
ALTER TABLE grc_issues ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE grc_issues ADD COLUMN IF NOT EXISTS closed_by uuid REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE grc_issues ADD COLUMN IF NOT EXISTS closed_at timestamptz;
CREATE TABLE IF NOT EXISTS grc_enterprise_risks(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES grc_organizations(id) ON DELETE CASCADE,risk_key text UNIQUE NOT NULL,
 title text NOT NULL,description text NOT NULL DEFAULT '',likelihood int NOT NULL CHECK(likelihood BETWEEN 1 AND 5),impact int NOT NULL CHECK(impact BETWEEN 1 AND 5),
 inherent_score int NOT NULL,inherent_rating text NOT NULL,treatment text NOT NULL CHECK(treatment IN ('MITIGATE','ACCEPT','TRANSFER','AVOID')),
 residual_likelihood int CHECK(residual_likelihood BETWEEN 1 AND 5),residual_impact int CHECK(residual_impact BETWEEN 1 AND 5),residual_score int,residual_rating text,
 owner_user_id uuid REFERENCES app_users(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','TREATMENT','ACCEPTANCE_PENDING','ACCEPTED','CLOSED')),
 acceptance_expires_at timestamptz,accepted_by uuid REFERENCES app_users(id) ON DELETE SET NULL,created_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS grc_issue_risks(issue_id uuid NOT NULL REFERENCES grc_issues(id) ON DELETE CASCADE,risk_id uuid NOT NULL REFERENCES grc_enterprise_risks(id) ON DELETE CASCADE,PRIMARY KEY(issue_id,risk_id));
CREATE TABLE IF NOT EXISTS grc_capa(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES grc_organizations(id) ON DELETE CASCADE,capa_key text UNIQUE NOT NULL,
 issue_id uuid NOT NULL REFERENCES grc_issues(id) ON DELETE CASCADE,root_cause text NOT NULL,corrective_action text NOT NULL,preventive_action text NOT NULL DEFAULT '',
 owner_user_id uuid REFERENCES app_users(id) ON DELETE SET NULL,priority text NOT NULL DEFAULT 'P2',status text NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','IN_PROGRESS','EVIDENCE_SUBMITTED','RETEST_PENDING','VALIDATION','CHANGES_REQUESTED','CLOSED','OVERDUE')),
 due_at timestamptz NOT NULL,retest_run_id uuid REFERENCES grc_control_test_runs(id) ON DELETE SET NULL,submitted_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
 approved_by uuid REFERENCES app_users(id) ON DELETE SET NULL,closed_at timestamptz,created_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS grc_capa_evidence(capa_id uuid NOT NULL REFERENCES grc_capa(id) ON DELETE CASCADE,evidence_version_id uuid NOT NULL REFERENCES grc_evidence_versions(id) ON DELETE RESTRICT,linked_by uuid REFERENCES app_users(id) ON DELETE SET NULL,linked_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(capa_id,evidence_version_id));
CREATE TABLE IF NOT EXISTS grc_record_events(id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES grc_organizations(id) ON DELETE CASCADE,record_type text NOT NULL,record_id uuid NOT NULL,event text NOT NULL,actor_user_id uuid REFERENCES app_users(id) ON DELETE SET NULL,reason text,snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS grc_capa_org_status_idx ON grc_capa(organization_id,status,due_at);CREATE INDEX IF NOT EXISTS grc_erisk_org_idx ON grc_enterprise_risks(organization_id,status,inherent_score DESC);
`)}
type Queryable={query:(text:string,values?:any[])=>Promise<any>};
async function event(org:string,type:string,id:string,eventName:string,actor:string,reason?:string,snapshot:any={},db:Queryable=pool){await db.query('INSERT INTO grc_record_events(id,organization_id,record_type,record_id,event,actor_user_id,reason,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[crypto.randomUUID(),org,type,id,eventName,actor,reason||null,snapshot])}
export async function listIssues(user:string,org:string){await requireOrgPermission(user,org,'read');return (await pool.query('SELECT * FROM grc_issues WHERE organization_id=$1 ORDER BY created_at DESC',[org])).rows}
export async function createRiskFromIssue(user:string,org:string,issueId:string,input:any){await requireOrgPermission(user,org,'manageRisk');const issue=(await pool.query('SELECT * FROM grc_issues WHERE id=$1 AND organization_id=$2',[issueId,org])).rows[0];if(!issue)throw Object.assign(new Error('Issue not found'),{statusCode:404});
 const l=Number(input.likelihood),i=Number(input.impact);if(!Number.isInteger(l)||!Number.isInteger(i)||l<1||l>5||i<1||i>5)throw new Error('Likelihood and impact must be 1-5');const score=l*i,t=String(input.treatment||'MITIGATE').toUpperCase();if(!['MITIGATE','ACCEPT','TRANSFER','AVOID'].includes(t))throw new Error('Invalid treatment');
 if(input.ownerUserId)await requireOrgPermission(input.ownerUserId,org,'read');const id=crypto.randomUUID();const client=await pool.connect();try{await client.query('BEGIN');const risk=(await client.query(`INSERT INTO grc_enterprise_risks(id,organization_id,risk_key,title,description,likelihood,impact,inherent_score,inherent_rating,treatment,owner_user_id,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[id,org,key('RISK'),String(input.title||issue.title),String(input.description||issue.description||''),l,i,score,riskBand(score),t,input.ownerUserId||null,t==='ACCEPT'?'ACCEPTANCE_PENDING':'TREATMENT',user])).rows[0];await client.query('INSERT INTO grc_issue_risks(issue_id,risk_id) VALUES($1,$2)',[issueId,id]);await event(org,'RISK',id,'CREATED',user,undefined,{issueId,score,treatment:t},client);await client.query('COMMIT');return risk}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function approveRiskAcceptance(user:string,org:string,riskId:string,input:any){await requireOrgPermission(user,org,'review');const r=(await pool.query('SELECT * FROM grc_enterprise_risks WHERE id=$1 AND organization_id=$2',[riskId,org])).rows[0];if(!r)throw Object.assign(new Error('Risk not found'),{statusCode:404});if(r.treatment!=='ACCEPT'||r.status!=='ACCEPTANCE_PENDING')throw Object.assign(new Error('Risk is not awaiting acceptance'),{statusCode:409});if(r.created_by===user||r.owner_user_id===user)throw Object.assign(new Error('Risk creator/owner cannot approve own acceptance'),{statusCode:409});const expiry=new Date(String(input.expiresAt||''));if(!Number.isFinite(expiry.getTime())||expiry<=new Date())throw new Error('Future acceptance expiry required');const client=await pool.connect();try{await client.query('BEGIN');const out=(await client.query(`UPDATE grc_enterprise_risks SET status='ACCEPTED',acceptance_expires_at=$2,accepted_by=$3,updated_at=now() WHERE id=$1 RETURNING *`,[riskId,expiry,user])).rows[0];await event(org,'RISK',riskId,'RISK_ACCEPTED',user,String(input.reason||''),{expiresAt:expiry.toISOString()},client);await client.query('COMMIT');return out}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function createCapa(user:string,org:string,issueId:string,input:any){await requireOrgPermission(user,org,'manageRisk');const issue=(await pool.query('SELECT * FROM grc_issues WHERE id=$1 AND organization_id=$2',[issueId,org])).rows[0];if(!issue)throw Object.assign(new Error('Issue not found'),{statusCode:404});const root=String(input.rootCause||'').trim(),action=String(input.correctiveAction||'').trim();if(root.length<5||action.length<5)throw new Error('Root cause and corrective action are required');const due=new Date(String(input.dueAt||''));if(!Number.isFinite(due.getTime())||due<=new Date())throw new Error('Future CAPA due date required');if(input.ownerUserId)await requireOrgPermission(input.ownerUserId,org,'read');const id=crypto.randomUUID();const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`INSERT INTO grc_capa(id,organization_id,capa_key,issue_id,root_cause,corrective_action,preventive_action,owner_user_id,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[id,org,key('CAPA'),issueId,root,action,String(input.preventiveAction||''),input.ownerUserId||null,String(input.priority||issue.priority||'P2'),due,user])).rows[0];await event(org,'CAPA',id,'CREATED',user,undefined,{issueId},client);await client.query('COMMIT');return row}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function submitCapaEvidence(user:string,org:string,capaId:string,evidenceVersionId:string){const c=(await pool.query('SELECT * FROM grc_capa WHERE id=$1 AND organization_id=$2',[capaId,org])).rows[0];if(!c)throw Object.assign(new Error('CAPA not found'),{statusCode:404});const m=await requireOrgPermission(user,org,'manageControl');if(c.owner_user_id&&c.owner_user_id!==user&&!['ORG_ADMIN','GRC_MANAGER','GRC_ANALYST'].includes(m.role))throw Object.assign(new Error('CAPA owner required'),{statusCode:403});const ev=(await pool.query(`SELECT v.id FROM grc_evidence_versions v JOIN grc_evidence_requests r ON r.id=v.evidence_request_id WHERE v.id=$1 AND r.organization_id=$2 AND r.status='VALID' AND v.valid_until>now()`,[evidenceVersionId,org])).rows[0];if(!ev)throw new Error('Current validated evidence version required');await pool.query('INSERT INTO grc_capa_evidence(capa_id,evidence_version_id,linked_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[capaId,evidenceVersionId,user]);const out=(await pool.query(`UPDATE grc_capa SET status='RETEST_PENDING',submitted_by=$2,updated_at=now() WHERE id=$1 RETURNING *`,[capaId,user])).rows[0];await event(org,'CAPA',capaId,'EVIDENCE_SUBMITTED',user,undefined,{evidenceVersionId});return out}
export async function attachRetest(user:string,org:string,capaId:string,testRunId:string){await requireOrgPermission(user,org,'review');const c=(await pool.query('SELECT * FROM grc_capa WHERE id=$1 AND organization_id=$2',[capaId,org])).rows[0];if(!c)throw Object.assign(new Error('CAPA not found'),{statusCode:404});const run=(await pool.query('SELECT * FROM grc_control_test_runs WHERE id=$1 AND organization_id=$2',[testRunId,org])).rows[0];if(!run)throw new Error('Retest run not found');const status=run.result==='PASS'?'VALIDATION':'CHANGES_REQUESTED';const out=(await pool.query('UPDATE grc_capa SET retest_run_id=$2,status=$3,updated_at=now() WHERE id=$1 RETURNING *',[capaId,testRunId,status])).rows[0];await event(org,'CAPA',capaId,'RETEST_'+run.result,user,run.rationale,{testRunId});return out}
export async function closeCapa(user:string,org:string,capaId:string,input:any){await requireOrgPermission(user,org,'review');const c=(await pool.query(`SELECT c.*,r.result retest_result FROM grc_capa c LEFT JOIN grc_control_test_runs r ON r.id=c.retest_run_id WHERE c.id=$1 AND c.organization_id=$2`,[capaId,org])).rows[0];if(!c)throw Object.assign(new Error('CAPA not found'),{statusCode:404});if(c.status!=='VALIDATION'||c.retest_result!=='PASS')throw Object.assign(new Error('Passing retest in validation state required'),{statusCode:409});if(c.created_by===user||c.owner_user_id===user||c.submitted_by===user)throw Object.assign(new Error('Independent reviewer required for CAPA closure'),{statusCode:409});const client=await pool.connect();try{await client.query('BEGIN');const out=(await client.query(`UPDATE grc_capa SET status='CLOSED',approved_by=$2,closed_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[capaId,user])).rows[0];await client.query(`UPDATE grc_issues SET status='CLOSED',closed_by=$2,closed_at=now(),updated_at=now() WHERE id=$1`,[c.issue_id,user]);await event(org,'CAPA',capaId,'CLOSED',user,String(input.reason||''),{retestRunId:c.retest_run_id},client);await client.query('COMMIT');return out}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function listCapa(user:string,org:string){await requireOrgPermission(user,org,'read');return (await pool.query(`SELECT c.*,CASE WHEN c.status<>'CLOSED' AND c.due_at<now() THEN true ELSE false END AS overdue FROM grc_capa c WHERE organization_id=$1 ORDER BY due_at ASC`,[org])).rows}
export async function listEnterpriseRisks(user:string,org:string){await requireOrgPermission(user,org,'read');return (await pool.query('SELECT * FROM grc_enterprise_risks WHERE organization_id=$1 ORDER BY inherent_score DESC,created_at DESC',[org])).rows}
