import { frameworkCatalog } from './grc.js';
export const learningModules=[
 {id:'grc-foundations',category:'GRC',level:'Foundation',title:'GRC Foundations',summary:'Connect governance, risk, controls, evidence, assurance and remediation without confusing a control mapping with certification.',topics:['risk vs issue vs finding','control design vs operating effectiveness','evidence provenance','residual risk','audit readiness']},
 {id:'iso27001',category:'Framework',level:'Intermediate',title:'ISO/IEC 27001:2022',summary:'Learn the ISMS lifecycle, risk treatment and how evidence supports control implementation. Aegis stores references and explanations, not copyrighted standard text.',topics:['ISMS scope','risk assessment','Statement of Applicability','control evidence','continual improvement']},
 {id:'iso42001',category:'Framework',level:'Intermediate',title:'ISO/IEC 42001:2023',summary:'AI management-system concepts for responsible governance, impact assessment, lifecycle controls and interested-party information.',topics:['AI policy','roles and accountability','AI impact assessment','AI lifecycle','monitoring and improvement']},
 {id:'nist-csf',category:'Framework',level:'Foundation',title:'NIST CSF 2.0',summary:'Understand Govern, Identify, Protect, Detect, Respond and Recover as cybersecurity outcome groups.',topics:['Govern','Identify','Protect','Detect','Respond','Recover']},
 {id:'nist-ai-rmf',category:'Framework',level:'Intermediate',title:'NIST AI RMF',summary:'Understand Govern, Map, Measure and Manage for AI risk.',topics:['Govern','Map','Measure','Manage']},
 {id:'owasp',category:'Application Security',level:'Foundation',title:'OWASP Application Security',summary:'Learn common web risk classes and how scanner observations become evidence-backed remediation work.',topics:['access control','injection','cryptography','misconfiguration','secure development']},
 {id:'evidence',category:'Assurance',level:'Advanced',title:'Evidence Engineering',summary:'Build traceable security conclusions from scanner, document and configuration evidence while separating observation from interpretation.',topics:['hash integrity','source provenance','confidence','false positives','verification']},
 {id:'architecture',category:'Architecture',level:'Advanced',title:'Security Architecture Reasoning',summary:'Separate observed architecture, documented architecture and correlated architecture before drawing trust boundaries and data flows.',topics:['assets','trust boundaries','data flows','attack surface','control placement']}
];
export function knowledgeCatalog(){return {updatedAt:'2026-10-07',frameworks:frameworkCatalog,modules:learningModules,notice:'Curated learning content is explanatory. Standards and laws should be verified against authoritative current publications; copyrighted standards text is not reproduced.'}}
