import PDFDocument from 'pdfkit'; import type { Assessment,Finding,Evidence } from './models.js';
const SEVS=['CRITICAL','HIGH','MEDIUM','LOW','INFO'] as const;
function counts(fs:Finding[]){return SEVS.map(s=>({name:s,n:fs.filter(f=>f.severity===s).length}))}
function chart(d:any,title:string,data:{name:string,n:number}[]){d.moveDown().fontSize(14).text(title);const x=d.x,y=d.y+8,w=250,h=14,max=Math.max(1,...data.map(v=>v.n));data.forEach((v,i)=>{const yy=y+i*24;d.fontSize(8).text(v.name,x,yy,{width:70});d.rect(x+72,yy,Math.max(2,(v.n/max)*w),h).fillOpacity(.55).fill('#22d3ee').fillOpacity(1);d.fillColor('#111827').fontSize(8).text(String(v.n),x+78+(v.n/max)*w,yy+2)});d.y=y+data.length*24+8}
export function renderPdf(a:Assessment,fs:Finding[],ev:Evidence[]=[]){return new Promise<Buffer>((resolve,reject)=>{const d=new PDFDocument({margin:48,bufferPages:true});const chunks:Buffer[]=[];d.on('data',x=>chunks.push(x));d.on('end',()=>resolve(Buffer.concat(chunks)));d.on('error',reject);
 d.fontSize(22).text('AegisGRC Full Security Assessment Report');d.moveDown().fontSize(10).text('Assessment: '+a.id).text('Target: '+a.target).text('Authorized: '+a.authorizedAt).text('Status: '+a.status).text('Generated: '+new Date().toISOString());
 const scored=fs.map(f=>Number(f.cvss)).filter(Number.isFinite);d.moveDown().fontSize(15).text('Executive Risk Summary');d.fontSize(10).text('Evidence-backed findings: '+fs.length).text('Highest CVSS: '+(scored.length?Math.max(...scored).toFixed(1):'N/A')).text('Stored tool evidence records: '+ev.length);
 chart(d,'Severity Distribution',counts(fs));chart(d,'CVSS Distribution',[{name:'Critical 9-10',n:scored.filter(x=>x>=9).length},{name:'High 7-8.9',n:scored.filter(x=>x>=7&&x<9).length},{name:'Medium 4-6.9',n:scored.filter(x=>x>=4&&x<7).length},{name:'Low 0.1-3.9',n:scored.filter(x=>x>0&&x<4).length}]);
 chart(d,'Testing Coverage',[...new Set(ev.map(e=>e.source))].map(source=>({name:source.toUpperCase(),n:ev.filter(e=>e.source===source).length})));
 d.addPage().fontSize(16).text('Offensive / Technical Testing Evidence');d.fontSize(9).text('Only tools actually executed are listed. Raw output is stored as evidence and hashed with SHA-256.');
 for(const e of ev){d.moveDown().fontSize(12).text(e.source.toUpperCase()+' · '+e.createdAt);d.fontSize(8).text('SHA-256: '+e.sha256+' | Exit: '+String(e.exitCode??'N/A')).text(('Output: '+(e.stdout||e.stderr||'No textual output stored')).slice(0,5000));}
 d.addPage().fontSize(16).text('Findings · Defensive Analysis · Remediation');
 if(!fs.length)d.fontSize(11).text('No normalized findings recorded.');
 for(const f of fs){d.moveDown().fontSize(12).text(f.severity+' · '+f.title);d.fontSize(9).text('CVSS: '+(f.cvss??'N/A')+' | CWE: '+(f.cwe??'N/A')+' | Source: '+f.source).text('Asset: '+f.asset).text('Evidence: '+f.evidenceHash).moveDown(.3).fontSize(10).text('What the test found').fontSize(9).text(f.description).moveDown(.2).fontSize(10).text('What this means').fontSize(9).text(f.severity==='INFO'?'This is an observed exposure or service condition. It is not automatically an exploitable vulnerability and should be interpreted with the service purpose and configuration.':f.severity==='LOW'?'This is a lower-risk weakness or hardening opportunity that should be reviewed in context.':f.severity==='MEDIUM'?'This is a meaningful weakness or exposure that should be remediated through the normal security process.':'This is a high-priority security finding and should receive prompt validation and remediation.').moveDown(.2).fontSize(10).text('Defensive remediation plan').fontSize(9).text(f.remediation||'Validate the affected control, reduce unnecessary exposure, apply the appropriate secure configuration or code fix, and retest.').moveDown(.2).fontSize(10).text('Validation after remediation').fontSize(9).text('Repeat the same authorized test that generated this evidence and verify that the condition is removed or restricted as intended.').text('OWASP: '+(f.mappings.owasp||[]).join(', ')).text('ISO 27001: '+(f.mappings.iso27001||[]).join(', ')).text('ISO 42001: '+(f.mappings.iso42001||[]).join(', ')).text('NIST: '+(f.mappings.nist||f.mappings.nistCsf||[]).join(', '));}
 d.moveDown().fontSize(8).text('Evidence note: AI guidance is advisory. Scanner/document evidence and hashes are the provenance source; framework mappings are cross-references and do not constitute certification.');
 d.end();})}