import crypto from 'node:crypto';import pg from 'pg';import QRCode from 'qrcode';
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}});
const sessions=new Map<string,{exp:number,userId:string,email:string}>(),TTL=8*60*60*1000;
function b32buf(s:string){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of s.toUpperCase().replace(/[^A-Z2-7]/g,'')){const n=a.indexOf(c);if(n>=0)bits+=n.toString(2).padStart(5,'0')}const out=[];for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out)}
function b32enc(b:Buffer){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const x of b)bits+=x.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5)out+=a[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out}
function totp(secret:string,step=Math.floor(Date.now()/30000)){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(step));const h=crypto.createHmac('sha1',b32buf(secret)).update(b).digest(),o=h[h.length-1]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,'0')}
function verify(secret:string,code:string){return /^\d{6}$/.test(code)&&[-1,0,1].some(d=>{const a=Buffer.from(code),b=Buffer.from(totp(secret,Math.floor(Date.now()/30000)+d));return a.length===b.length&&crypto.timingSafeEqual(a,b)})}
function hashPassword(p:string,salt=crypto.randomBytes(16)){return {salt:salt.toString('hex'),hash:crypto.scryptSync(p,salt,64).toString('hex')}}
function pass(p:string,salt:string,hash:string){const h=crypto.scryptSync(p,Buffer.from(salt,'hex'),64),x=Buffer.from(hash,'hex');return h.length===x.length&&crypto.timingSafeEqual(h,x)}
export async function initUsers(){await pool.query('CREATE TABLE IF NOT EXISTS app_users(id uuid PRIMARY KEY,email text UNIQUE NOT NULL,password_hash text NOT NULL,password_salt text NOT NULL,totp_secret text NOT NULL,totp_verified boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())')}
export async function beginRegistration(email:string,password:string){email=email.trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<10)throw Error('Valid email and password of at least 10 characters required');const secret=b32enc(crypto.randomBytes(20)),h=hashPassword(password),id=crypto.randomUUID();await pool.query('INSERT INTO app_users(id,email,password_hash,password_salt,totp_secret,totp_verified) VALUES($1,$2,$3,$4,$5,false)',[id,email,h.hash,h.salt,secret]);const otpauth='otpauth://totp/'+encodeURIComponent('AegisGRC:'+email)+'?secret='+secret+'&issuer='+encodeURIComponent('AegisGRC');const qrDataUrl=await QRCode.toDataURL(otpauth,{errorCorrectionLevel:'M',margin:2,width:220});return {userId:id,email,secret,qrDataUrl}}
export async function confirmRegistration(userId:string,code:string){const r=await pool.query('SELECT * FROM app_users WHERE id=$1',[userId]),u=r.rows[0];if(!u||!verify(u.totp_secret,code))return false;await pool.query('UPDATE app_users SET totp_verified=true WHERE id=$1',[userId]);return true}
export async function userLogin(email:string,password:string,code:string){const r=await pool.query('SELECT * FROM app_users WHERE email=$1',[email.trim().toLowerCase()]),u=r.rows[0];if(!u||!u.totp_verified||!pass(password,u.password_salt,u.password_hash)||!verify(u.totp_secret,code))return null;const token=crypto.randomBytes(32).toString('base64url');sessions.set(token,{exp:Date.now()+TTL,userId:u.id,email:u.email});return token}
export function userSession(token:string){const s=sessions.get(token);if(!s||s.exp<Date.now()){sessions.delete(token);return null}return s}
export function userLogout(token:string){sessions.delete(token)}
